[global]
pid = /run/hestia-php.pid
error_log = /var/log/hestia/php-fpm.log
log_level = error

emergency_restart_threshold = 10
emergency_restart_interval = 60s
process_control_timeout = 10s
events.mechanism = epoll

include=/etc/php/hestia/fpm/pool.d/*.conf
