# HestiaRE web bot rate-limiting (Layer B) - server-native, CrowdSec-independent.
# Native nginx limit_req / apache mod_qos throttling of bot families (429 on excess). Humans are
# UNLIMITED; malicious traffic is CrowdSec's job (ban -> 403), never here. Available on ANY web
# install (nginx-only, apache-only, both), whether or not CrowdSec is installed.
#
# Model: an admin bot-family table (share/botpolicy/botfamilies.conf, seeded to
# /etc/hestia/botfamilies.conf). Each family = name / UA match / lenient+strict rate / enabled,
# plus conf-only advanced burst + nodelay. Per domain each family is off/lenient/strict (the
# web.conf BOTLIMIT field). nginx keys per-family aggregate (one bucket per family); apache mod_qos
# counts per client IP. get_object_value/search_objects take the object base and append .conf.

# Seed the instance family conf (survives updates) from the shipped default if absent.
botpolicy_seed_families() {
	mkdir -p "$CONF_DIR"
	[ -f "$CONF_DIR/botfamilies.conf" ] \
		|| cp -f "$HESTIA/share/botpolicy/botfamilies.conf" "$CONF_DIR/botfamilies.conf"
}

# "120r/m" -> "120 60"; "2r/s" -> "2 1" (count + window seconds for mod_qos). Fallback "60 60".
botpolicy_rate_to_qos() {
	local r="$1" n u
	n=${r%%r/*}
	u=${r##*r/}
	case "$u" in s) echo "${n:-60} 1" ;; *) echo "${n:-60} 60" ;; esac
}

# Render the nginx UA map + per-family limit_req zones into /etc/nginx/conf.d/hestia_botlimit.conf.
# Aggregate keying; 'generic' is always emitted LAST in the UA map (first match wins).
botpolicy_render_nginx() {
	local obj="$CONF_DIR/botfamilies"
	local out="/etc/nginx/conf.d/hestia_botlimit.conf"
	[ -f "$obj.conf" ] || return 0

	local enabled f match len strict has_generic=''
	enabled=$(search_objects "$obj" 'ENABLED' 'yes' 'FAMILY')

	local tmp
	tmp=$(mktemp)
	{
		echo "# HestiaRE web bot rate-limit (Layer B) - GENERATED from $obj.conf. Edit the conf,"
		echo "# then run h-update-sys-botfamilies to re-render. Do not edit this file directly."
		echo "limit_req_status 429;"
		echo
		echo "map \$http_user_agent \$hbot_fam {"
		echo "	default \"\";"
		for f in $enabled; do
			[ "$f" = 'generic' ] && { has_generic=1; continue; }
			match=$(get_object_value "$obj" 'FAMILY' "$f" '$MATCH')
			[ -n "$match" ] && echo "	\"~*($match)\" \"$f\";"
		done
		if [ -n "$has_generic" ]; then
			match=$(get_object_value "$obj" 'FAMILY' 'generic' '$MATCH')
			[ -n "$match" ] && echo "	\"~*($match)\" \"generic\";"
		fi
		echo "}"
		echo
		# Per family: an aggregate key (constant per family, empty otherwise) + the two rate zones.
		# 1m holds the single aggregate key with room to spare; a vhost selects a zone via limit_req.
		for f in $enabled; do
			len=$(get_object_value "$obj" 'FAMILY' "$f" '$LENIENT')
			strict=$(get_object_value "$obj" 'FAMILY' "$f" '$STRICT')
			echo "map \$hbot_fam \$hbot_k_$f { default \"\"; \"$f\" \"$f\"; }"
			[ -n "$len" ] && echo "limit_req_zone \$hbot_k_$f zone=hbot_${f}_lenient:1m rate=$len;"
			[ -n "$strict" ] && echo "limit_req_zone \$hbot_k_$f zone=hbot_${f}_strict:1m rate=$strict;"
		done
	} > "$tmp"
	mv -f "$tmp" "$out"
	chmod 644 "$out"
}

# Render the apache mod_qos base + a per-family per-level event counter into
# /etc/apache2/conf.d/hestia_botlimit.conf. mod_qos counts per client IP (no aggregate), 429 on
# breach; the per-domain fragment sets the QS_Event_<fam>_<level> var.
botpolicy_render_apache() {
	local obj="$CONF_DIR/botfamilies"
	local out="/etc/apache2/conf.d/hestia_botlimit.conf"
	[ -f "$obj.conf" ] || return 0

	local enabled f len strict n win
	enabled=$(search_objects "$obj" 'ENABLED' 'yes' 'FAMILY')
	local tmp
	tmp=$(mktemp)
	{
		echo "# HestiaRE web bot rate-limit (Layer B, apache mod_qos) - GENERATED from $obj.conf."
		echo "# Edit the conf, then run h-update-sys-botfamilies. Do not edit this file directly."
		echo "QS_ClientEntries 100000"
		echo "QS_ErrorResponseCode 429"
		for f in $enabled; do
			len=$(get_object_value "$obj" 'FAMILY' "$f" '$LENIENT')
			strict=$(get_object_value "$obj" 'FAMILY' "$f" '$STRICT')
			read -r n win < <(botpolicy_rate_to_qos "$len")
			echo "QS_ClientEventLimitCount $n $win QS_Event_${f}_lenient"
			read -r n win < <(botpolicy_rate_to_qos "$strict")
			echo "QS_ClientEventLimitCount $n $win QS_Event_${f}_strict"
		done
	} > "$tmp"
	mv -f "$tmp" "$out"
	chmod 644 "$out"
}

# Re-render the active web front's Layer-B server config + reload. nginx fronts in nginx-only/both;
# apache-only is the only model where apache does Layer B.
botpolicy_apply() {
	local pub
	if [ -n "$PROXY_SYSTEM" ]; then pub="$PROXY_SYSTEM"; else pub="$WEB_SYSTEM"; fi
	if [ "$pub" = "nginx" ]; then
		botpolicy_render_nginx
		nginx -t > /dev/null 2>&1 && { systemctl reload nginx > /dev/null 2>&1 || systemctl restart nginx > /dev/null 2>&1; }
	elif [ "$WEB_SYSTEM" = "apache2" ]; then
		botpolicy_render_apache
		apache2ctl configtest > /dev/null 2>&1 && { systemctl reload apache2 > /dev/null 2>&1 || systemctl restart apache2 > /dev/null 2>&1; }
	fi
}

# Render the per-domain Layer-B fragment (nginx.botlimit.conf / botlimit.apache2.conf) from the
# domain's BOTLIMIT field ("fam:level,fam:level"; level = lenient|strict, absent = off). Removed
# when empty, so the vhost's IncludeOptional/include glob is a no-op for unthrottled domains.
botpolicy_render_domain_fragment() {
	local user="$1" domain="$2" sys
	if [ -n "$PROXY_SYSTEM" ]; then sys="$PROXY_SYSTEM"; else sys="$WEB_SYSTEM"; fi

	local rec bl
	rec=$(grep -m1 "DOMAIN='$domain'" "$CONF_DIR/users/$user/web.conf" 2> /dev/null)
	[ -n "$rec" ] || return 0
	bl=$(sed -n "s/.*BOTLIMIT='\([^']*\)'.*/\1/p" <<< "$rec")

	local obj="$CONF_DIR/botfamilies"
	local frag tmp entry fam lvl burst nodelay nd match
	tmp=$(mktemp)

	if [ "$sys" = "nginx" ]; then
		frag="$HOMEDIR/$user/conf/web/$domain/nginx.botlimit.conf"
		# shellcheck disable=SC2086 # comma-split of the compact BOTLIMIT field is intentional
		for entry in ${bl//,/ }; do
			fam=${entry%%:*}
			lvl=${entry#*:}
			case "$lvl" in lenient | strict) ;; *) continue ;; esac
			burst=$(get_object_value "$obj" 'FAMILY' "$fam" '$BURST' 2> /dev/null)
			nodelay=$(get_object_value "$obj" 'FAMILY' "$fam" '$NODELAY' 2> /dev/null)
			[ -n "$burst" ] || burst=10
			nd=""
			[ "$nodelay" = "yes" ] && nd=" nodelay"
			echo "limit_req zone=hbot_${fam}_${lvl} burst=${burst}${nd};" >> "$tmp"
		done
	elif [ "$sys" = "apache2" ]; then
		frag="$HOMEDIR/$user/conf/web/$domain/botlimit.apache2.conf"
		# shellcheck disable=SC2086 # comma-split of the compact BOTLIMIT field is intentional
		for entry in ${bl//,/ }; do
			fam=${entry%%:*}
			lvl=${entry#*:}
			case "$lvl" in lenient | strict) ;; *) continue ;; esac
			match=$(get_object_value "$obj" 'FAMILY' "$fam" '$MATCH' 2> /dev/null)
			[ -n "$match" ] || continue
			echo "BrowserMatchNoCase \"$match\" hbot_$fam" >> "$tmp"
			echo "SetEnvIf hbot_$fam 1 QS_Event_${fam}_${lvl}" >> "$tmp"
		done
	else
		rm -f "$tmp"
		return 0
	fi

	if [ -s "$tmp" ]; then
		mv -f "$tmp" "$frag"
		chown root:"$user" "$frag"
		chmod 640 "$frag"
	else
		rm -f "$tmp" "$frag"
	fi
}
