# .gitea/workflows/push-to-github.yml
name: Push to GitHub

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # manueller Button im UI

jobs:
  mirror:
    runs-on: hestiare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push main + tag to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git remote add github https://FalzoMAD:${GITHUB_TOKEN}@github.com/FalzoMAD/HestiaRE.git
          git push github main
          git push github ${{ gitea.ref_name }}