#!/bin/bash

# Hestia Control Panel upgrade script for target version 1.3.3

#######################################################################################
#######                      Place additional commands below.                   #######
#######################################################################################

# Check if keys folder exists and adjust permissions
if [ -d "$HESTIA/data/keys" ]; then
	echo '[ * ] Update permissions'
	chmod 750 "$HESTIA/data/keys"
	chown admin:root "$HESTIA/data/keys"
fi

if [[ ! -e /etc/hestia/hestia.conf ]]; then
	echo '[ * ] Create global Hestia config'

	mkdir -p /etc/hestia
	echo -e "# Do not edit this file, will get overwritten on next upgrade, use /etc/hestia/local.conf instead\n\nexport HESTIA='/usr/local/hestia'\n\n[[ -f /etc/hestia/local.conf ]] && source /etc/hestia/local.conf" > /etc/hestia/hestia.conf
fi
